/* The following code was generated by JFlex 1.4.3 on 12.08.13 13:27 */

package com.antonzherdev.objd;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import com.antonzherdev.objd.psi.ObjDTypes;
import com.intellij.psi.TokenType;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 12.08.13 13:27 from the specification file
 * <tt>/Users/antonzherdev/dev/objd-idea-plugin/src/com/antonzherdev/objd/ObjD.flex</tt>
 */
class ObjDLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int COMMENT_STATE = 2;
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\1\0\10\0\1\1\1\6\1\0\1\1\1\3\22\0\1\1\1\60"+
    "\1\5\3\0\1\55\1\0\1\46\1\47\1\4\1\56\1\50\1\10"+
    "\1\12\1\2\12\11\1\51\1\0\1\52\1\53\1\41\1\57\1\0"+
    "\32\7\1\44\1\0\1\45\1\0\1\7\1\0\1\14\1\36\1\15"+
    "\1\31\1\20\1\32\1\17\1\40\1\23\1\7\1\16\1\21\1\24"+
    "\1\34\1\25\1\13\1\7\1\26\1\22\1\27\1\35\1\30\1\37"+
    "\1\33\2\7\1\42\1\54\1\43\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\4\1\1\1\5\1\6"+
    "\1\7\1\10\16\5\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\2\1\1\24"+
    "\1\25\1\26\4\27\1\30\1\31\1\32\1\0\1\33"+
    "\1\34\1\7\1\35\1\36\1\0\11\5\1\37\7\5"+
    "\1\40\10\5\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\1\51\1\52\13\5\1\53\4\5\1\54"+
    "\1\55\1\5\1\56\2\5\1\57\10\5\1\60\1\5"+
    "\1\61\1\62\3\5\1\63\3\5\1\64\1\5\1\65"+
    "\2\5\1\66\1\67\1\5\1\70\3\5\1\71\6\5"+
    "\1\72\1\73\1\74\1\75\1\76\1\77\3\5\1\100"+
    "\1\101\1\102\1\103\1\104\1\105\1\106\1\107";

  private static int [] zzUnpackAction() {
    int [] result = new int[169];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\142\0\223\0\304\0\365\0\u0126\0\u0157"+
    "\0\u0188\0\u01b9\0\142\0\u01ea\0\u021b\0\u024c\0\u027d\0\u02ae"+
    "\0\u02df\0\u0310\0\u0341\0\u0372\0\u03a3\0\u03d4\0\u0405\0\u0436"+
    "\0\u0467\0\u0498\0\142\0\142\0\142\0\142\0\142\0\142"+
    "\0\142\0\142\0\u04c9\0\u04fa\0\u052b\0\u055c\0\u058d\0\142"+
    "\0\u05be\0\142\0\223\0\u05ef\0\u0620\0\142\0\142\0\142"+
    "\0\u0126\0\u0126\0\142\0\u0651\0\142\0\142\0\u0682\0\u06b3"+
    "\0\u06e4\0\u0715\0\u0746\0\u0777\0\u07a8\0\u07d9\0\u080a\0\u083b"+
    "\0\u0157\0\u086c\0\u089d\0\u08ce\0\u08ff\0\u0930\0\u0961\0\u0992"+
    "\0\u0157\0\u09c3\0\u09f4\0\u0a25\0\u0a56\0\u0a87\0\u0ab8\0\u0ae9"+
    "\0\u0b1a\0\142\0\142\0\142\0\142\0\142\0\142\0\142"+
    "\0\142\0\142\0\u0682\0\u0b4b\0\u0b7c\0\u0bad\0\u0bde\0\u0c0f"+
    "\0\u0c40\0\u0c71\0\u0ca2\0\u0cd3\0\u0d04\0\u0d35\0\u0157\0\u0d66"+
    "\0\u0d97\0\u0dc8\0\u0df9\0\u0157\0\u0157\0\u0e2a\0\u0157\0\u0e5b"+
    "\0\u0e8c\0\u0157\0\u0ebd\0\u0eee\0\u0f1f\0\u0f50\0\u0f81\0\u0fb2"+
    "\0\u0fe3\0\u1014\0\u0157\0\u1045\0\u0157\0\u0157\0\u1076\0\u10a7"+
    "\0\u10d8\0\u0157\0\u1109\0\u113a\0\u116b\0\u0157\0\u119c\0\u0157"+
    "\0\u11cd\0\u11fe\0\u0157\0\u0157\0\u122f\0\u0157\0\u1260\0\u1291"+
    "\0\u12c2\0\u0157\0\u12f3\0\u1324\0\u1355\0\u1386\0\u13b7\0\u13e8"+
    "\0\u0157\0\u0157\0\u0157\0\u0157\0\u0157\0\u0157\0\u1419\0\u144a"+
    "\0\u147b\0\u0157\0\u0157\0\u0157\0\u0157\0\u0157\0\u0157\0\u0157"+
    "\0\u0157";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[169];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\4\1\6\1\7\1\4\1\10"+
    "\1\11\1\12\1\13\1\14\1\10\1\15\2\10\1\16"+
    "\1\10\1\17\1\20\2\10\1\21\1\22\1\23\1\24"+
    "\1\25\1\10\1\26\1\27\1\30\1\31\1\10\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\51\1\52"+
    "\1\53\1\52\1\53\1\54\1\52\1\4\52\52\62\0"+
    "\1\4\1\0\1\4\2\0\1\4\54\0\1\55\1\0"+
    "\1\56\46\0\1\57\60\0\1\60\5\0\5\61\1\62"+
    "\1\0\52\61\7\0\1\10\1\0\1\10\1\0\26\10"+
    "\30\0\1\63\1\64\27\0\1\65\11\0\1\66\14\0"+
    "\1\10\1\0\1\12\1\67\26\10\27\0\1\10\1\0"+
    "\1\10\1\0\1\10\1\70\11\10\1\71\12\10\27\0"+
    "\1\10\1\0\1\10\1\0\6\10\1\72\17\10\27\0"+
    "\1\10\1\0\1\10\1\0\6\10\1\73\11\10\1\74"+
    "\1\75\4\10\27\0\1\10\1\0\1\10\1\0\5\10"+
    "\1\76\6\10\1\77\11\10\27\0\1\10\1\0\1\10"+
    "\1\0\11\10\1\100\5\10\1\101\1\10\1\102\4\10"+
    "\27\0\1\10\1\0\1\10\1\0\5\10\1\103\20\10"+
    "\27\0\1\10\1\0\1\10\1\0\13\10\1\104\11\10"+
    "\1\105\27\0\1\10\1\0\1\10\1\0\1\10\1\106"+
    "\10\10\1\107\13\10\27\0\1\10\1\0\1\10\1\0"+
    "\5\10\1\110\4\10\1\111\13\10\27\0\1\10\1\0"+
    "\1\10\1\0\1\10\1\112\4\10\1\113\17\10\27\0"+
    "\1\10\1\0\1\10\1\0\10\10\1\114\15\10\27\0"+
    "\1\10\1\0\1\10\1\0\10\10\1\115\15\10\27\0"+
    "\1\10\1\0\1\10\1\0\12\10\1\116\1\117\12\10"+
    "\27\0\1\10\1\0\1\10\1\0\5\10\1\120\17\10"+
    "\1\121\73\0\1\122\60\0\1\123\60\0\1\124\61\0"+
    "\1\125\61\0\1\126\56\0\1\127\2\0\1\130\55\0"+
    "\1\131\7\0\1\132\56\0\3\55\1\0\2\55\1\0"+
    "\52\55\11\0\1\64\1\67\57\0\1\133\56\0\1\10"+
    "\1\0\1\10\1\0\2\10\1\134\23\10\27\0\1\10"+
    "\1\0\1\10\1\0\10\10\1\135\15\10\27\0\1\10"+
    "\1\0\1\10\1\0\1\10\1\136\24\10\27\0\1\10"+
    "\1\0\1\10\1\0\7\10\1\137\16\10\27\0\1\10"+
    "\1\0\1\10\1\0\14\10\1\140\11\10\27\0\1\10"+
    "\1\0\1\10\1\0\22\10\1\141\3\10\27\0\1\10"+
    "\1\0\1\10\1\0\6\10\1\142\17\10\27\0\1\10"+
    "\1\0\1\10\1\0\1\10\1\143\11\10\1\144\6\10"+
    "\1\145\3\10\27\0\1\10\1\0\1\10\1\0\1\146"+
    "\25\10\27\0\1\10\1\0\1\10\1\0\14\10\1\147"+
    "\11\10\27\0\1\10\1\0\1\10\1\0\14\10\1\150"+
    "\11\10\27\0\1\10\1\0\1\10\1\0\1\10\1\151"+
    "\20\10\1\152\3\10\27\0\1\10\1\0\1\10\1\0"+
    "\13\10\1\153\12\10\27\0\1\10\1\0\1\10\1\0"+
    "\6\10\1\154\4\10\1\155\12\10\27\0\1\10\1\0"+
    "\1\10\1\0\10\10\1\156\15\10\27\0\1\10\1\0"+
    "\1\10\1\0\17\10\1\157\6\10\27\0\1\10\1\0"+
    "\1\10\1\0\6\10\1\160\17\10\27\0\1\10\1\0"+
    "\1\10\1\0\12\10\1\161\13\10\27\0\1\10\1\0"+
    "\1\10\1\0\6\10\1\162\17\10\27\0\1\10\1\0"+
    "\1\10\1\0\21\10\1\163\4\10\27\0\1\10\1\0"+
    "\1\10\1\0\12\10\1\164\13\10\27\0\1\10\1\0"+
    "\1\10\1\0\5\10\1\165\20\10\27\0\1\10\1\0"+
    "\1\10\1\0\1\10\1\166\24\10\27\0\1\10\1\0"+
    "\1\10\1\0\10\10\1\167\15\10\27\0\1\10\1\0"+
    "\1\10\1\0\3\10\1\170\22\10\27\0\1\10\1\0"+
    "\1\10\1\0\15\10\1\171\10\10\27\0\1\10\1\0"+
    "\1\10\1\0\7\10\1\172\16\10\27\0\1\10\1\0"+
    "\1\10\1\0\5\10\1\173\20\10\27\0\1\10\1\0"+
    "\1\10\1\0\5\10\1\174\20\10\27\0\1\10\1\0"+
    "\1\10\1\0\11\10\1\175\14\10\27\0\1\10\1\0"+
    "\1\10\1\0\17\10\1\176\6\10\27\0\1\10\1\0"+
    "\1\10\1\0\14\10\1\177\11\10\27\0\1\10\1\0"+
    "\1\10\1\0\10\10\1\200\11\10\1\201\3\10\27\0"+
    "\1\10\1\0\1\10\1\0\23\10\1\202\2\10\27\0"+
    "\1\10\1\0\1\10\1\0\12\10\1\203\13\10\27\0"+
    "\1\10\1\0\1\10\1\0\22\10\1\204\3\10\27\0"+
    "\1\10\1\0\1\10\1\0\10\10\1\205\15\10\27\0"+
    "\1\10\1\0\1\10\1\0\5\10\1\206\20\10\27\0"+
    "\1\10\1\0\1\10\1\0\12\10\1\207\13\10\27\0"+
    "\1\10\1\0\1\10\1\0\16\10\1\210\7\10\27\0"+
    "\1\10\1\0\1\10\1\0\7\10\1\211\16\10\27\0"+
    "\1\10\1\0\1\10\1\0\1\10\1\212\24\10\27\0"+
    "\1\10\1\0\1\10\1\0\14\10\1\213\11\10\27\0"+
    "\1\10\1\0\1\10\1\0\6\10\1\214\17\10\27\0"+
    "\1\10\1\0\1\10\1\0\1\10\1\215\24\10\27\0"+
    "\1\10\1\0\1\10\1\0\3\10\1\216\22\10\27\0"+
    "\1\10\1\0\1\10\1\0\6\10\1\217\17\10\27\0"+
    "\1\10\1\0\1\10\1\0\1\10\1\220\24\10\27\0"+
    "\1\10\1\0\1\10\1\0\1\10\1\221\24\10\27\0"+
    "\1\10\1\0\1\10\1\0\7\10\1\222\16\10\27\0"+
    "\1\10\1\0\1\10\1\0\21\10\1\223\4\10\27\0"+
    "\1\10\1\0\1\10\1\0\10\10\1\224\15\10\27\0"+
    "\1\10\1\0\1\10\1\0\21\10\1\225\4\10\27\0"+
    "\1\10\1\0\1\10\1\0\2\10\1\226\23\10\27\0"+
    "\1\10\1\0\1\10\1\0\13\10\1\227\12\10\27\0"+
    "\1\10\1\0\1\10\1\0\13\10\1\230\12\10\27\0"+
    "\1\10\1\0\1\10\1\0\14\10\1\231\11\10\27\0"+
    "\1\10\1\0\1\10\1\0\24\10\1\232\1\10\27\0"+
    "\1\10\1\0\1\10\1\0\5\10\1\233\20\10\27\0"+
    "\1\10\1\0\1\10\1\0\14\10\1\234\11\10\27\0"+
    "\1\10\1\0\1\10\1\0\3\10\1\235\22\10\27\0"+
    "\1\10\1\0\1\10\1\0\5\10\1\236\20\10\27\0"+
    "\1\10\1\0\1\10\1\0\4\10\1\237\21\10\27\0"+
    "\1\10\1\0\1\10\1\0\14\10\1\240\11\10\27\0"+
    "\1\10\1\0\1\10\1\0\16\10\1\241\7\10\27\0"+
    "\1\10\1\0\1\10\1\0\2\10\1\242\23\10\27\0"+
    "\1\10\1\0\1\10\1\0\4\10\1\243\21\10\27\0"+
    "\1\10\1\0\1\10\1\0\14\10\1\244\11\10\27\0"+
    "\1\10\1\0\1\10\1\0\14\10\1\245\11\10\27\0"+
    "\1\10\1\0\1\10\1\0\21\10\1\246\4\10\27\0"+
    "\1\10\1\0\1\10\1\0\5\10\1\247\20\10\27\0"+
    "\1\10\1\0\1\10\1\0\5\10\1\250\20\10\27\0"+
    "\1\10\1\0\1\10\1\0\7\10\1\251\16\10\20\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5292];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\7\1\1\11\17\1\10\11\5\1\1\11"+
    "\1\1\1\11\3\1\3\11\1\0\1\1\1\11\1\1"+
    "\2\11\1\0\32\1\11\11\117\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[169];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;


  ObjDLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  ObjDLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 132) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL.charAt(zzCurrentPosL++);
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL.charAt(zzCurrentPosL++);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 10: 
          { return ObjDTypes.OPEN_BRACE;
          }
        case 72: break;
        case 67: 
          { return ObjDTypes.W_IMPORT;
          }
        case 73: break;
        case 6: 
          { return ObjDTypes.MINUS;
          }
        case 74: break;
        case 50: 
          { return ObjDTypes.W_SELF;
          }
        case 75: break;
        case 44: 
          { return ObjDTypes.W_VAL;
          }
        case 76: break;
        case 60: 
          { return ObjDTypes.W_FALSE;
          }
        case 77: break;
        case 32: 
          { return ObjDTypes.W_DO;
          }
        case 78: break;
        case 45: 
          { return ObjDTypes.W_VAR;
          }
        case 79: break;
        case 4: 
          { return ObjDTypes.MUL;
          }
        case 80: break;
        case 61: 
          { return ObjDTypes.TP_FLOAT;
          }
        case 81: break;
        case 5: 
          { return ObjDTypes.IDENT;
          }
        case 82: break;
        case 46: 
          { return ObjDTypes.W_DEF;
          }
        case 83: break;
        case 39: 
          { return ObjDTypes.PLUS_PLUS;
          }
        case 84: break;
        case 41: 
          { yybegin(YYINITIAL); return ObjDTypes.COMMENT;
          }
        case 85: break;
        case 25: 
          { return ObjDTypes.DIV_SET;
          }
        case 86: break;
        case 33: 
          { return ObjDTypes.MOREEQ;
          }
        case 87: break;
        case 49: 
          { return ObjDTypes.W_ENUM;
          }
        case 88: break;
        case 2: 
          { return TokenType.WHITE_SPACE;
          }
        case 89: break;
        case 24: 
          { yybegin(COMMENT_STATE); return ObjDTypes.COMMENT;
          }
        case 90: break;
        case 68: 
          { return ObjDTypes.W_RETURN;
          }
        case 91: break;
        case 48: 
          { return ObjDTypes.W_ELSE;
          }
        case 92: break;
        case 15: 
          { return ObjDTypes.CLOSE_BRACKET;
          }
        case 93: break;
        case 22: 
          { return ObjDTypes.EXCLAMATION;
          }
        case 94: break;
        case 66: 
          { return ObjDTypes.W_STRUCT;
          }
        case 95: break;
        case 12: 
          { return ObjDTypes.OPEN_SQUARE_BRACKET;
          }
        case 96: break;
        case 14: 
          { return ObjDTypes.OPEN_BRACKET;
          }
        case 97: break;
        case 21: 
          { return ObjDTypes.WHAT;
          }
        case 98: break;
        case 40: 
          { return ObjDTypes.NOT_EQ;
          }
        case 99: break;
        case 18: 
          { return ObjDTypes.LESS;
          }
        case 100: break;
        case 52: 
          { return ObjDTypes.W_TRUE;
          }
        case 101: break;
        case 58: 
          { return ObjDTypes.W_TRAIT;
          }
        case 102: break;
        case 64: 
          { return ObjDTypes.W_STATIC;
          }
        case 103: break;
        case 29: 
          { return ObjDTypes.ARROW;
          }
        case 104: break;
        case 35: 
          { return ObjDTypes.EQ;
          }
        case 105: break;
        case 59: 
          { return ObjDTypes.W_THROW;
          }
        case 106: break;
        case 57: 
          { return ObjDTypes.W_CLASS;
          }
        case 107: break;
        case 31: 
          { return ObjDTypes.W_IF;
          }
        case 108: break;
        case 51: 
          { return ObjDTypes.W_STUB;
          }
        case 109: break;
        case 70: 
          { return ObjDTypes.W_PRIVATE;
          }
        case 110: break;
        case 8: 
          { return ObjDTypes.DOT;
          }
        case 111: break;
        case 63: 
          { return ObjDTypes.W_WHILE;
          }
        case 112: break;
        case 3: 
          { return ObjDTypes.DIV;
          }
        case 113: break;
        case 28: 
          { return ObjDTypes.MINUS_MINUS;
          }
        case 114: break;
        case 34: 
          { return ObjDTypes.LESSEQ;
          }
        case 115: break;
        case 71: 
          { return ObjDTypes.W_EXTENDS;
          }
        case 116: break;
        case 56: 
          { return ObjDTypes.W_WEAK;
          }
        case 117: break;
        case 37: 
          { return ObjDTypes.AND;
          }
        case 118: break;
        case 23: 
          { return ObjDTypes.COMMENT;
          }
        case 119: break;
        case 13: 
          { return ObjDTypes.CLOSE_SQUARE_BRACKET;
          }
        case 120: break;
        case 62: 
          { return ObjDTypes.W_BREAK;
          }
        case 121: break;
        case 16: 
          { return ObjDTypes.COMMA;
          }
        case 122: break;
        case 7: 
          { return ObjDTypes.INT;
          }
        case 123: break;
        case 1: 
          { return TokenType.BAD_CHARACTER;
          }
        case 124: break;
        case 53: 
          { return ObjDTypes.TP_VOID;
          }
        case 125: break;
        case 54: 
          { return ObjDTypes.TP_UINT;
          }
        case 126: break;
        case 27: 
          { return ObjDTypes.STRING;
          }
        case 127: break;
        case 17: 
          { return ObjDTypes.COLON;
          }
        case 128: break;
        case 65: 
          { return ObjDTypes.TP_STRING;
          }
        case 129: break;
        case 38: 
          { return ObjDTypes.PLUS_SET;
          }
        case 130: break;
        case 26: 
          { return ObjDTypes.MUL_SET;
          }
        case 131: break;
        case 19: 
          { return ObjDTypes.SET;
          }
        case 132: break;
        case 30: 
          { return ObjDTypes.MINUS_SET;
          }
        case 133: break;
        case 43: 
          { return ObjDTypes.TP_INT;
          }
        case 134: break;
        case 47: 
          { return ObjDTypes.W_NIL;
          }
        case 135: break;
        case 69: 
          { return ObjDTypes.W_PACKAGE;
          }
        case 136: break;
        case 55: 
          { return ObjDTypes.TP_BOOL;
          }
        case 137: break;
        case 9: 
          { return ObjDTypes.MORE;
          }
        case 138: break;
        case 11: 
          { return ObjDTypes.CLOSE_BRACE;
          }
        case 139: break;
        case 20: 
          { return ObjDTypes.PLUS;
          }
        case 140: break;
        case 36: 
          { return ObjDTypes.OR;
          }
        case 141: break;
        case 42: 
          { return ObjDTypes.FLOAT;
          }
        case 142: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
